"""Main web service entry point."""

from __future__ import annotations

from contextlib import asynccontextmanager
from typing import TYPE_CHECKING

from fastapi import FastAPI, Request, Response, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from eclipse_tracker import logging_setup
from eclipse_tracker.api import eclipses, itinerary, recommendations
from eclipse_tracker.config.config import (
    initialize_logging,
    settings,
)


if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Awaitable, Callable


@asynccontextmanager
async def lifespan(instance: FastAPI) -> AsyncGenerator[None]:
    """Manage app lifecycle."""
    instance.settings = settings
    logging_setup.get_logger(__name__).info("application_startup_completed", app_name=settings.service.app_name)
    yield
    logging_setup.get_logger(__name__).info("application_shutdown_completed")


initialize_logging()
app = FastAPI(lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors.allow_origins,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(eclipses.router)
app.include_router(recommendations.router)
app.include_router(itinerary.router)


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """Turn unhandled errors into a normal JSON response so CORSMiddleware still adds its headers.

    Starlette's default 500 fallback is generated by ServerErrorMiddleware, which sits outside
    CORSMiddleware in the stack - the browser sees a CORS failure instead of the real error.
    Registering a handler here keeps the response inside the middleware stack.
    """
    logging_setup.get_logger(__name__).exception("unhandled_exception", path=request.url.path, error=str(exc))
    return JSONResponse(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, content={"detail": "Internal server error"})


@app.middleware("http")
async def process_request(request: Request, call_next: Callable[[Request], Awaitable[Response]]) -> Response:
    """Middleware to perform actions before and after handling the request."""
    # Perform any necessary actions before processing the request
    # Example actions: modifying headers, checking authentication, etc.
    # ....

    response = await call_next(request)

    # Perform any necessary actions after processing the request
    # Example actions: modifying the response, adding cookies, etc.
    # ....
    return response  # noqa: RET504


def say(message: str = "Hello World!") -> None:
    """Say a message."""
    return message


@app.get("/dummy/{item_id}")
async def read_item(item_id: int) -> JSONResponse:
    """Read item."""
    content = {"item_id": item_id, "message": say()}
    return JSONResponse(content=content, status_code=status.HTTP_200_OK)


@app.get("/alive", status_code=status.HTTP_204_NO_CONTENT)
async def alive() -> None:
    """Check if service is alive."""
    return
