#!/usr/bin/env python3
"""
Generate code for reference.

This script facilitates the generation of documentation pages for the codebase,
utilizing the `mkdocs_gen_files` and `mkdocstrings` libraries
to create structured documentation based on the source code structure.

The generated documentation pages are stored in Markdown format
and are intended to provide an organized reference for the codebase.

The script iterates through Python files in the specified directories,
processes them to extract module and function documentation,
and creates corresponding Markdown files.

If specified, a warning can be inserted at the beginning of the generated files indicating
that they are auto-generated and should not be edited manually.

Parameters
----------
- code_path: str
    The path to the directory containing the Python code files to be documented.
- target_path: str
    The path where the generated documentation files will be saved.
- exclude_files_by_name: list, optional
    A list of filenames to be excluded from documentation generation.
- insert_warning: bool, optional
    A flag indicating whether to insert a warning message in the generated files.

Usage
-----
Call the `generate_documentation` function, specifying the code path, target path,
and any optional parameters as needed.

Example:
    generate_documentation("voice_csp_service",
                           "references/api/voice_csp_service",
                           ["__main__", "_meta"])
    generate_documentation("scripts", "references/api/scripts")

References
----------
- mkdocstrings: A library for generating documentation from docstrings.
  [Learn more](https://mkdocstrings.github.io)
- mkdocs_gen_files: A library for generating documentation files for MkDocs.
  [Learn more](https://oprypin.github.io/mkdocs-gen-files/index.html)

Note: This script is intended to be run as part of a documentation generation workflow,
ensuring that the codebase documentation remains up-to-date and accessible.
"""

from pathlib import Path

import mkdocs_gen_files


def generate_documentation(
    code_path: str,
    target_path: str,
    exclude_files_by_name: list | None = None,
    exclude_paths: list | None = None,
    *,
    insert_warning: bool = False,
) -> None:
    """Generate the documentation from code."""
    for path in sorted(Path(code_path).rglob("*.py")):
        if exclude_paths and str(path).split("/", 1)[1].rpartition("/")[0] in exclude_paths:
            continue

        module_path = path.relative_to(code_path).with_suffix("")
        doc_path = path.relative_to(code_path).with_suffix(".md")
        full_doc_path = Path(target_path, doc_path)

        parts = list(module_path.parts)
        parts.insert(0, code_path)  # Append prefix lib to avoid location problem
        if exclude_files_by_name and parts[-1] in exclude_files_by_name:
            continue

        # Set up init as module index with its description
        if parts[-1] == "__init__":
            parts = parts[:-1]
            doc_path = doc_path.with_name("index.md")
            full_doc_path = full_doc_path.with_name("index.md")

        # Generate on-the-fly the documentation,
        # just add the warning and put the identifier for mkdocstrings
        with mkdocs_gen_files.open(full_doc_path, "w") as fd:
            if insert_warning:
                message = "This page is meant to be autogenerated from code. Do not edit it manually."
                print(f"???+ warning\n\t{message}", file=fd)
            identifier = ".".join(parts)
            print("::: " + identifier, file=fd)

        mkdocs_gen_files.set_edit_path(full_doc_path, path)


generate_documentation(
    "src",
    Path("references/integration/code"),
    ["__main__", "_meta"],
)
generate_documentation("scripts", "references/integration/code/scripts")
